### ISSUE TITLE
App cannot load data

### ISSUE THREAD

**Issue by bartaelterman** [cambecc/air#1]
Hi,

I am trying to get the air application running locally. Everything goes well, except launching the server. I am not sure what to use as <air-data-url>. I filled in the url that is mentioned in the README where the data comes from, and I notice in the server output that it is trying to connect to http://www.kankyo.metro.tokyo.jp/p160.cgi?no2===1==2====2= but that results in a custom "page not found", and the server throws an "error: no data found". When I point my browser to the local application, it says "-1 Cannot load resource: /data/wind/current"

How should I go about this?

Thanks!

**Comment by cambecc** [comment]
I think the URL has changed. It is now located at http://www.taiki.kankyo.metro.tokyo.jp.

**Comment by bartaelterman** [comment]
If I use that url, I get a “403 Forbidden" response. Looks like they locked things up?

**Comment by cambecc** [comment]
odd. just successfully visited now.
