### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by peterdesmet** [cambecc/air#3]
Hi @cambecc,

Our team hacked together a flow visualization of bird migration over the Netherlands and Belgium recorded by weather radars. It is online at:

http://enram.github.io/bird-migration-flow-visualization/viz/

Source code is on [GitHub](https://github.com/enram/bird-migration-flow-visualization).

We were inspired by [air](https://github.com/cambecc/air/) and used parts of your code, for which we would like to thank you.

Cheers,

[LifeWatch INBO](https://twitter.com/LifeWatchINBO) team (@peterdesmet, @bartaelterman, @kazijn)

**Comment by cambecc** [comment]
This is awesome! Nicely done. What steps are you planning to take next?

**Comment by peterdesmet** [comment]
Just back from holiday. Thanks for the feedback.

Regarding next steps: this was a prototype and we plan to build upon it, but not in the coming months and not just by us.

[ENRAM](http://enram.eu) plans to organize a [visualization challenge](https://github.com/enram/bird-migration-flow-visualization/blob/master/documentation/stsm-report.md#discuss-aim-and-structure-of-the-visualization-challenge) at the end of this year, to see what others can do with the data (i.e. other visualizations).

We would like to extend our visualization by including bird density, heatmaps, and more control over the story. These are just early [milestones](https://github.com/enram/bird-migration-flow-visualization/issues/milestones?with_issues=no), we'll wait from feedback from the researchers to see what they want most.

The ultimate goal is to have this (and other) visualizations for all of Europe, but the data does not exist yet, which is what ENRAM is trying to solve.

In any way, it was very cool to work (and hopefully continue to work) on this.
