### ISSUE TITLE
Different Values

### ISSUE THREAD

**Issue by fflajom** [cambecc/air#4]
Hi Mr Cameron, 

When selecting the overlay wind velocity, there is a difference in both values?

**Comment by cambecc** [comment]
Not sure I understand what you mean. Can you please describe more?

**Comment by fflajom** [comment]
Hi Mr Cameron. 

I selected the WV overlay and here is a sample output after clicking a point.

340º @ 1.9 m/s | 2.5 m/s. Why is there a difference in the values?

**Comment by cambecc** [comment]
Yes, this behavior is a little weird. You are viewing two different layers:
1. animation of wind
2. color overlay of wind speed

These two layers use different interpolation methods. The first uses Inverse Distance Weighting interpolation, and the second uses Thin Plate Spline interpolation. They have different behavior and thus result in two different values.

There is no good reason to have two different interpolation methods for the same data. It was simply an experiment.
